export const BettyPrefabs = {
  AUTO_COMPLETE: 'Autocomplete',
  BOOLEAN: 'Checkbox',
  DATE: 'DatePicker',
  DATE_TIME: 'DateTimePicker',
  DECIMAL: 'Decimal',
  EMAIL_ADDRESS: 'Email',
  HIDDEN: 'Hidden',
  IBAN: 'IBAN',
  INTEGER: 'Number',
  LIST: 'Select',
  MULTI_AUTO_COMPLETE: 'Multi Autocomplete',
  PASSWORD: 'Password',
  PHONE_NUMBER: 'Phone',
  PRICE: 'Price',
  RADIO: 'Radio',
  RICH_TEXT: 'Rich Text Editor',
  SELECT: 'Select',
  STRING: 'Text Field',
  SUBMIT_BUTTON: 'Submit Button',
  TEXT: 'Text Area',
  TIME: 'TimePicker',
  UPDATE_FORM: 'Update Form',
  URL: 'Url',
  FILE: 'File Upload',
  IMAGE: 'Image Upload',
  LOGIN_FORM: 'Login Form',
  CREATE_FORM: 'Create Form',
  FORM: 'Form',
};
