export const BettyPrefabs = {
  AUTO_COMPLETE: 'Autocomplete Beta',
  BOOLEAN: 'Checkbox Beta',
  DATE: 'DatePicker Beta',
  DATE_TIME: 'DateTimePicker Beta',
  DECIMAL: 'Decimal Beta',
  EMAIL_ADDRESS: 'Email Beta',
  HIDDEN: 'Hidden Beta',
  IBAN: 'IBAN Beta',
  INTEGER: 'Number Beta',
  LIST: 'Select Beta',
  MULTI_AUTO_COMPLETE: 'Multi Autocomplete Beta',
  PASSWORD: 'Password Beta',
  PHONE_NUMBER: 'Phone Beta',
  PRICE: 'Price Beta',
  RADIO: 'Radio Beta',
  SELECT: 'Select Beta',
  STRING: 'Text Field Beta',
  SUBMIT_BUTTON: 'Submit Button',
  TEXT: 'Text Area Beta',
  TIME: 'TimePicker Beta',
  UPDATE_FORM: 'Update Form Beta',
  URL: 'Url Beta',
};
