name: Release
on:
  workflow_run:
    workflows: [Generate Docs]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js 16.11.1
        uses: actions/setup-node@v1
        with:
          node-version: '16.11.1'
      - run: npm install
      - name: Run build
        run: npm run build
      - name: Release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
