name: Release
on:
  workflow_run:
    workflows: [Generate Docs]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Use Node.js 22.4.1
        uses: actions/setup-node@v4
        with:
          node-version: '22.4.1'
      - run: npm install
      - name: Run build
        run: npm run build
      - name: Release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
